server:
  port: 34002
spring:
  activemq:
    broker-url: tcp://192.168.25.153:61616
#######microservice-dysms##########
accessKeyId: LTAIp96fRQOZEkdb
accessKeySecret: qFMPQHLCFbAzNAgVYMj0MS3ZbdXZ4A
templateCode: SMS_142105268
#activemq-to-sendSms-switch#
activemqToSendSms: false
