# 服务器配置
server:
  port: 8040
# Spring相关配置
spring:
  application:
    name: ms-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      perfer-ip-address: true
